on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '[0-9]+.[0-9]+.[0-9]' # real actual release
      - 'rust-**'             # a test for new rust compiler version

name: Release

jobs:
  build:
    name: Rust ${{ matrix.rust }} / OS ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
        rust: ['1.48.0']

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: echo ${{ github.event.release.tag_name }}
#      - name: Create Release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
#        with:
#          tag_name: ${{ github.ref }}
#          release_name: ${{ github.ref }}
#          draft: true
#          prerelease: false
